### ISSUE TITLE
Autoconvert not true by default

### ISSUE THREAD

**Issue by pinta83** [nhammadi/Smileys#5]
Documentation says
"You can disable the auto-conversion of smileys by setting the auto_convert_smileys configuration option to false", and by that one would assume that the default value is true, when it's undefined.
For auto conversion to work, you have to explicitly define a parameter

auto_convert_smileys: true

**Comment by nhammadi** [comment]
Thanks pinta83 for your comment
You're right, By default the smileys auto conversion is disabled so you have to set the  auto_convert_smileys configuration option  to true in order to enable it.

I just fixed this in the readme file. Thanks again and please don't hesitate to submit any bug, issue you find in this plugin

**Comment by pinta83** [comment]
No problem m8, if i find anything else, I'll report ASAP :)
